### ISSUE TITLE
settings are not merged between all and env

### ISSUE THREAD

**Issue by laurent-indermuehle** [redhat-cop/aap_configuration_template#46]
When I set controller_settings_all and controller_settings_dev, only the last value wins.
I was expended the variables to be merged.

For instance; 
```yaml
controller_settings_all:
  settings:
    GALAXY_IGNORE_CERTS: true
    AUTH_BASIC_ENABLED: true

controller_settings_dev:
  settings:
    TOWER_URL_BASE: https://aap-control-dev.example.com
```
When using:  `controller_settings: "{{ controller_settings_all | combine(controller_settings_dev, list_merge='append') }}"`
Then `control_settings` become: 

```yaml
settings:
  TOWER_URL_BASE: https://aap-control-dev.example.com
```

I was expecting:

```yaml
settings:
  GALAXY_IGNORE_CERTS: true
  AUTH_BASIC_ENABLED: true
  TOWER_URL_BASE: https://aap-control-dev.example.com
```
